Resources: 
  #===== IAM Users
  HelloUserAlice:
    Type: AWS::IAM::User
    Properties:
      Groups: 
        - !Ref HelloGroupSre
      LoginProfile:
          Password: !Ref InitialPassword
          PasswordResetRequired: true
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/IAMUserChangePassword'
      UserName: alice.alligator
      
  HelloUserBob:
    Type: AWS::IAM::User
    Properties:
      Groups: 
        - !Ref HelloGroupDev
      LoginProfile:
          Password: !Ref InitialPassword
          PasswordResetRequired: true
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/IAMUserChangePassword'
      UserName: bob.badger

  #===== IAM Groups
  HelloGroupDev: 
    Type: AWS::IAM::Group
    Properties: 
      GroupName: hello-group-dev
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
  
  HelloGroupSre: 
    Type: AWS::IAM::Group
    Properties: 
      GroupName: hello-group-sre
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AmazonVPCReadOnlyAccess'

  ##### BEGIN NEW ADDITIONS #####
  #===== IAM Roles
  HelloRoleDev:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            Effect: Allow
            Principal: 
              AWS: 
                - !GetAtt HelloUserAlice.Arn
                - !GetAtt HelloUserBob.Arn
            Action: 
              - 'sts:AssumeRole'
        Description: Hello Role Dev
        ManagedPolicyArns: 
          - arn:aws:iam::aws:policy/AmazonS3FullAccess
        RoleName: DEV

  HelloRoleSre:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Principal: 
            AWS: 
              - !GetAtt HelloUserAlice.Arn
              - !GetAtt HelloUserBob.Arn
          Action: 
            - 'sts:AssumeRole'
      Description: Role created via CloudFormation,
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonVPCFullAccess
      RoleName: SRE
  ##### END NEW ADDITIONS #####

Parameters:
  InitialPassword:
    Type: String
    Description: "Each of the users will have this initial password, and be prompted to change it."