Resources:
  #===== ECS
  # Don't think I even want this? it's for defining capacity?
  # HelloEcs:
  #   Type: AWS::ECS::Service
  #   Properties: 
  #     Cluster: !Ref HelloCluster
  #     DesiredCount: 1
  #     LaunchType: 'FARGATE'
  #     NetworkConfiguration: 
  #       AwsvpcConfiguration:
  #         Subnets: 
  #           - !Ref HelloSubnet
  #     SchedulingStrategy: 'REPLICA'
  #     ServiceName: 'hello-ecs'
  #     TaskDefinition: !Ref HelloTask

  HelloCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - 'FARGATE'
      ClusterName: 'hello-cluster'

  HelloTask:
    DependsOn: HelloLogGroup
    Type: AWS::ECS::TaskDefinition
    Properties: 
      Cpu: 256 
      ContainerDefinitions: 
        - Command: 
          - '/hello'
          Image: 'docker.io/library/hello-world:latest'
          LogConfiguration:
            LogDriver: 'awslogs'
            Options: 
              awslogs-group: !Ref HelloLogGroup
              awslogs-region: 'us-east-1'
              awslogs-stream-prefix: 'hello-task-stream'
          Name: 'hello-task-container'
          StopTimeout: 10
      ExecutionRoleArn: !GetAtt HelloRole.Arn
      Family: 'hello-task-family'
      Memory: 512
      NetworkMode: 'awsvpc'
      RequiresCompatibilities: 
        - 'FARGATE'
      Tags: 
        - Key: 'Name'
          Value: 'Hello Task'

  HelloLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: 'hello-task-log-group'

  #===== IAM
  HelloRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect: 'Allow'
          Principal: 
            Service: 
              - 'ecs-tasks.amazonaws.com'
          Action: 
            - 'sts:AssumeRole'
      Description: 'Hello Role'
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
      RoleName: 'hello-role'

  # HelloRole2:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Statement:
  #         Effect: 'Allow'
  #         Principal: 
  #           Service: 
  #             - 'ecs.amazonaws.com'
  #         Action: 
  #           - 'sts:AssumeRole'
  #     Description: 'Hello Role'
  #     ManagedPolicyArns: 
  #       - 'arn:aws:iam::aws:policy/aws-service-role/AmazonECSServiceRolePolicy'
  #     RoleName: 'hello-role2'    