Resources: 
  HelloBucket: 
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private

      ##### BEGIN NEW ADDITIONS #####
      BucketEncryption: 
        ServerSideEncryptionConfiguration:   
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      ##### END NEW ADDITIONS #####

      BucketName: !Sub 
        - 'hello-bucket-${Suffix}'
        - Suffix:  !Ref UniqueSuffix
      
  ##### BEGIN NEW ADDITIONS #####
  HelloBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket:  !Ref HelloBucket
      PolicyDocument: 
        Statement: 
          Principal: '*'
          Action: '*'
          Effect: Allow
          Resource: !Sub
            - arn:aws:s3:::${TargetBucketName}/*
            - TargetBucketName:  !Ref HelloBucket
  ##### END NEW ADDITIONS #####

Parameters: 
  UniqueSuffix: 
    AllowedPattern: ^[\d\w]{5,}$
    Type: String
    Description: Suffixed identifier to provide uniqueness on all names

Outputs : 
  HelloBucketArn: 
    Description: HelloBucket ARN
    Value:  !GetAtt HelloBucket.Arn