Resources: 
  #===== IAM
  HelloRole: 
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          Effect: 'Allow'
          Principal:  
            Service: 's3.amazonaws.com' 
          Action: 
            - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      RoleName: !Sub
        - 'hello-role-${Suffix}'
        - Suffix: !Ref UniqueSuffix 

  #===== S3
  HelloBucket: 
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketEncryption: 
        ServerSideEncryptionConfiguration:   
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      BucketName: !Sub 
        - 'hello-bucket-${Suffix}'
        - Suffix: !Ref UniqueSuffix
      ##### BEGIN NEW ADDITIONS #####
      ReplicationConfiguration: 
        Role: !GetAtt HelloRole.Arn
        Rules: 
          - Destination : 
              Bucket: !GetAtt HelloReplicate.Arn
            Status : 'Enabled'
      VersioningConfiguration: 
        Status: 'Enabled'
      ##### END NEW ADDITIONS #####
      
  HelloBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket:  !Ref HelloBucket
      PolicyDocument: 
        Statement: 
          Principal: '*'
          Action: '*'
          Effect: Allow
          Resource: !Sub
            - arn:aws:s3:::${TargetBucketName}/*
            - TargetBucketName:  !Ref HelloBucket
  ##### BEGIN NEW ADDITIONS #####
  HelloReplicate: 
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub
        - 'hello-replicate-${Suffix}'
        - Suffix: !Ref UniqueSuffix 
      VersioningConfiguration:  
        Status: Enabled 
  ##### END NEW ADDITIONS #####

Parameters: 
  UniqueSuffix: 
    AllowedPattern: ^[\d\w]{5,}$
    Type: String
    Description: Suffixed identifier to provide uniqueness on all names