Resources: 
  ##### BEGIN NEW ADDITIONS #####
  #===== IAM
  HelloRole: 
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          Effect: 'Allow'
          Principal:  
            Service: 's3.amazonaws.com' 
          Action: 
            - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      RoleName: !Sub
        - 'hello-role-${Suffix}'
        - Suffix: !Ref UniqueSuffix 

  #===== S3
  ##### END NEW ADDITIONS #####

  HelloBucket: 
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketEncryption: 
        ServerSideEncryptionConfiguration:   
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      BucketName: !Sub 
        - 'hello-bucket-${Suffix}'
        - Suffix:  !Ref UniqueSuffix
      
  HelloBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket:  !Ref HelloBucket
      PolicyDocument: 
        Statement: 
          Principal: '*'
          Action: '*'
          Effect: 'Allow'
          Resource: !Sub
            - arn:aws:s3:::${TargetBucketName}/*
            - TargetBucketName:  !Ref HelloBucket

Parameters: 
  UniqueSuffix: 
    AllowedPattern: ^[\d\w]{5,}$
    Type: String
    Description: Suffixed identifier to provide uniqueness on all names