Resources: 
  #===== VPC + IGW
  HelloVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.16.0.0/16
      Tags: 
        - Key: "Name"
          Value: "Hello VPC"
  
  HelloIgw:
    Type: AWS::EC2::InternetGateway
      
  HelloVpcIgwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref HelloIgw 
      VpcId: !Ref HelloVpc

  #===== Subnet
  HelloSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock: 10.16.0.0/24
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: "Name"
          Value: "Hello Public Subnet"
      VpcId: !Ref HelloVpc

  #===== Route Table
  HelloRt:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: "Name"
          Value: "Hello RT"
      VpcId: !Ref HelloVpc

  HelloRouteIPv4:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref HelloIgw 
      RouteTableId: !Ref HelloRt   
  
  HelloRtAssociate:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref HelloRt 
      SubnetId: !Ref HelloSubnet