Mappings:
  Meta:
    AvailabilityZone: 'us-east-1a'
    ImageId: 'ami-04bf6dcdc9ab498ca'
    InstanceType: 't2.micro'
    UniqueSuffix: 'e3'

Resources: 
  HelloInstanceA: 
    Type: AWS::EC2::Instance
    Properties: 
        AvailabilityZone: 'us-east-1a'
        IamInstanceProfile: !Ref HelloInstanceProfile
        ImageId: !FindInMap [ Meta, ImageId ]
        InstanceType: !FindInMap [ Meta, InstanceType ]
        Tags: 
          - Key: 'Name'
            Value: 'Hello Instance A'
  
  HelloInstanceB: 
    Type: AWS::EC2::Instance
    Properties: 
        AvailabilityZone: 'us-east-1a'
        IamInstanceProfile: !Ref HelloInstanceProfile
        ImageId: 'ami-04bf6dcdc9ab498ca'
        InstanceType: 't2.micro'
        Tags: 
          - Key: 'Name'
            Value: 'Hello Instance B'
        
  #===== IAM
  HelloRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect: 'Allow'
          Principal: 
            Service: 
              - 'ec2.amazonaws.com'
          Action: 
            - 'sts:AssumeRole'
      Description: 'Hello Role'
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      RoleName: 'hello-role-REMOVE_THIS_IDENTIFIER'

  HelloInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: 'hello-instance-profile-REMOVE_THIS_IDENTIFIER'
      Roles: 
        - !Ref HelloRole