Resources: 
  HelloSubnet: 
    DependsOn: HelloVpcCidrBlock
    Type: AWS::EC2::Subnet
    Properties: 
        AssignIpv6AddressOnCreation: true
        AvailabilityZone: 'us-east-1'
        CidrBlock:  Fn::Select: [ 0,  Fn::Cidr: [ Fn::GetAtt: [ HelloVpc, CidrBlock ], 1, 8 ]]
        Ipv6CidrBlock:  Fn::Select: [ 0,  Fn::Cidr: [ Fn::Select: [ 0,  Fn::GetAtt: [ HelloVpc, Ipv6CidrBlocks ]  ] , 1, 64 ] ]
        Tags: [ Key: Name, Value: Hello IPV6 Subnet ]
        VpcId:  Ref: HelloVpc 
      
  HelloVpc: 
    Type: AWS::EC2::VPC
    Properties: 
        CidrBlock: 10.16.0.0/16
        Tags: 
          - Key: 'Name'
            Value: 'Hello VPC'
      
  HelloVpcCidrBlock: 
    Type: AWS::EC2::VPCCidrBlock
    Properties: 
        AmazonProvidedIpv6CidrBlock: true
        VpcId: !Ref HelloVpc 
        
    
  

