Resources: 
  
  ##### BEGIN NEW ADDITIONS #####

  #===== EC2 Instance
  HelloInstance: 
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT3M
    Properties: 
      AvailabilityZone: 'us-east-1a'
      IamInstanceProfile: !Ref HelloInstanceProfile
      ImageId: ami-04bf6dcdc9ab498ca
      InstanceType: 't2.micro'
      SubnetId:  !Ref HelloSubnet 
      Tags: 
        - Key: 'Name'
          Value: 'Hello Instance'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum -y update
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource HelloInstance --configsets cwagent --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource HelloInstance --region ${AWS::Region}
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          cwagent:
            - installCloudwatchAgent
        installCloudwatchAgent:
          packages:
            yum:
              amazon-cloudwatch-agent: []
      
  ##### END NEW ADDITIONS #####

  #===== SSM
  HelloSsmParameter:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: 'hello-ssm-parameter'
      Type: 'String'
      Value: 
        '{
          "agent": {
            "metrics_collection_interval": 10
          },
          "logs": {
            "logs_collected": {
              "files": {
                "collect_list": [
                  {
                    "file_path": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log",
                    "log_group_name": "hello-log-group.log",
                    "timezone": "UTC"
                  }
                ]
              }
            },
            "log_stream_name": "hello-log-stream"
          }
        }'

  #===== IAM
  HelloRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect: 'Allow'
          Principal: 
            Service: 
              - 'ec2.amazonaws.com'
          Action: 
            - 'sts:AssumeRole'
      Description: 'Hello Role'
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
        - 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
      RoleName: 'hello-role'

  HelloInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: 'hello-instance-profile'
      Roles: 
        - !Ref HelloRole

  #===== VPC + IGW
  HelloVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.16.0.0/16'
      Tags: 
        - Key: 'Name'
          Value: 'Hello VPC'
  
  HelloIgw:
    Type: AWS::EC2::InternetGateway
      
  HelloVpcIgwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref HelloIgw 
      VpcId: !Ref HelloVpc

  #===== Subnet
  HelloSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'us-east-1a'
      CidrBlock: '10.16.0.0/24'
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: 'Name'
          Value: 'Hello Public Subnet'
      VpcId: !Ref HelloVpc

  #===== Route Table
  HelloRt:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: 'Name'
          Value: 'Hello RT'
      VpcId: !Ref HelloVpc

  HelloRouteIPv4:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref HelloIgw 
      RouteTableId: !Ref HelloRt   

  HelloRtAssociate:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref HelloRt 
      SubnetId: !Ref HelloSubnet