
  ##### BEGIN NEW ADDITIONS #####

  #===== EBS
  HelloVolume:
    Type: AWS::EC2::Volume
    Properties: 
      AvailabilityZone: !GetAtt HelloInstance.AvailabilityZone
      Encrypted: true
      Size: 1
      Tags: 
        - Key: 'Name'
          Value: 'Hello Volume'

  HelloVolumeAttach:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/sdh
      InstanceId: !Ref HelloInstance
      VolumeId: !Ref HelloVolume

  ##### END NEW ADDITIONS #####
