Resources: 
  #===== Flow Logs
  HelloFlowLogVpc: 
    Type: AWS::EC2::FlowLog
    Properties: 
      DeliverLogsPermissionArn: !GetAtt HelloFlowLogRole.Arn
      LogGroupName: "hello-flow-log-group"
      ResourceId: !Ref HelloVpc 
      ResourceType: VPC
      Tags: 
        - Key: "Name"
          Value: "Hello Flow Log VPC"
      TrafficType: ALL
  
  HelloFlowLogSubnet: 
    Type: AWS::EC2::FlowLog
    Properties: 
      DeliverLogsPermissionArn: !GetAtt HelloFlowLogRole.Arn
      LogGroupName: "hello-flow-log-group"
      ResourceId: !Ref HelloSubnet 
      ResourceType: Subnet
      Tags: 
        - Key: "Name"
          Value: "Hello Flow Log Subnet"
      TrafficType: ALL

  HelloFlowLogEni: 
    Type: AWS::EC2::FlowLog
    Properties: 
      DeliverLogsPermissionArn: !GetAtt HelloFlowLogRole.Arn
      LogGroupName: "hello-flow-log-group"
      ResourceId: !Ref HelloEni
      ResourceType: NetworkInterface
      Tags: 
        - Key: "Name"
          Value: "Hello Flow Log Network Interface"
      TrafficType: ALL

  HelloFlowLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: "hello-flow-log-group"

  HelloFlowLogRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Statement:
          Effect: 'Allow'
          Principal: 
            Service:
              - vpc-flow-logs.amazonaws.com
          Action: 
            - 'sts:AssumeRole'     
      Description: "Hello Flow Log Role"
      Policies:
        - PolicyName: "hello-flow-log-policy"
          PolicyDocument: 
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Effect: 'Allow'
                Resource: "*"
      RoleName: hello-flow-log-role

  #===== EC2 Instance
  HelloInstance: 
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: 'us-east-1a'
      IamInstanceProfile: !Ref HelloInstanceProfile
      ImageId: ami-04bf6dcdc9ab498ca
      InstanceType: 't2.micro'
      SubnetId: !Ref HelloSubnet 
      Tags: 
        - Key: "Name"
          Value: "Hello Instance"

  #===== IAM
  HelloRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect: 'Allow'
          Principal: 
            Service: 
              - 'ec2.amazonaws.com'
          Action: 
            - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      RoleName: 'hello-role'

  HelloInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: 'hello-instance-profile'
      Roles: 
        - !Ref HelloRole

  HelloEni:
    Type: AWS::EC2::NetworkInterface
    Properties: 
      SecondaryPrivateIpAddressCount: 1
      SubnetId: !Ref HelloSubnet
      Tags: 
        - Key: "Name"
          Value: "Hello ENI"

  HelloEniAttach:
    Type: AWS::EC2::NetworkInterfaceAttachment
    Properties: 
      DeviceIndex: 1
      InstanceId: !Ref HelloInstance
      NetworkInterfaceId: !Ref HelloEni

  #===== VPC
  HelloVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.16.0.0/16'
      Tags: 
        - Key: "Name"
          Value: "Hello VPC"
  
  HelloIgw:
    Type: AWS::EC2::InternetGateway
      
  HelloVpcIgwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref HelloIgw 
      VpcId: !Ref HelloVpc

  #===== Subnet
  HelloSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'us-east-1a'
      CidrBlock: '10.16.0.0/24'
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: "Name"
          Value: "Hello Public Subnet"
      VpcId: !Ref HelloVpc

  #===== Route Table
  HelloRt:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: "Name"
          Value: "Hello RT"
      VpcId: !Ref HelloVpc

  HelloRouteIPv4:
    Type: AWS::EC2::Route
    Properties:
        DestinationCidrBlock: '0.0.0.0/0'
        GatewayId: !Ref HelloIgw 
        RouteTableId: !Ref HelloRt   
  
  HelloRtAssociate:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref HelloRt 
      SubnetId: !Ref HelloSubnet
