Parameters: 
  UniqueSuffix: 
    AllowedPattern: ^[\d\w]{5,}$
    Type: String
    Description: Suffixed identifier to provide uniqueness on all S3 buckets

Resources: 
  #===== Bucket creation
  HelloBucketSource: 
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketEncryption: 
        ServerSideEncryptionConfiguration:   
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: 'AES256'
      BucketName: !Sub 
        - 'hello-source-${Suffix}'
        - Suffix: !Ref UniqueSuffix
      ReplicationConfiguration: 
        Role: !GetAtt HelloRole.Arn
        Rules: 
          - Destination : 
              Bucket: !GetAtt HelloBucketDestination.Arn
            Status : 'Enabled'
      VersioningConfiguration: 
        Status: 'Enabled'

  HelloBucketDestination: 
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketEncryption: 
        ServerSideEncryptionConfiguration:   
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: 'AES256'
      BucketName: !Sub
        - 'hello-destination-${Suffix}'
        - Suffix: !Ref UniqueSuffix 
      VersioningConfiguration:  
        Status: Enabled 

  #===== Bucket policy
  HelloBucketSourcePolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref HelloBucketSource
      PolicyDocument: 
        Statement: 
          Principal: '*'
          Action: '*'
          Effect: 'Allow'
          Resource: !Sub
            - arn:aws:s3:::${TargetBucketName}/*
            - TargetBucketName: !Ref HelloBucketSource

  #===== IAM
  HelloRole: 
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          Effect: 'Allow'
          Principal:  
            Service: 's3.amazonaws.com' 
          Action: 
            - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      RoleName: !Sub
        - 'hello-role-${Suffix}'
        - Suffix: !Ref UniqueSuffix 