Mappings:
  Application:
    Settings:
      UniqueSuffix: 'e12'

Resources:
  HelloEcrHttpd:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: 'hello-ecr-httpd'
      
  HelloCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders:
        - HelloCapacityProvider
      ClusterName: !Sub
        - 'hello-cluster-${UniqueSuffix}'
        - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]

  HelloCapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties: 
      AutoScalingGroupProvider: 
        AutoScalingGroupArn: String
      Name: String
      Tags: 
        - Tag

  HelloTask:
    # DependsOn: HelloLogGroup
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions: 
        # - Command: 
        #   - '/hello'
        - Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${HelloEcrHttpd}:latest'
          # LogConfiguration:
          #   LogDriver: 'awslogs'
          #   Options: 
          #     awslogs-group: !Ref HelloLogGroup
          #     awslogs-region: !Sub ${AWS::Region}
          #     awslogs-stream-prefix: !Sub
          #       - 'hello-task-stream-${UniqueSuffix}'
          #       - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]
          Name: !Sub
            - 'hello-task-container-${UniqueSuffix}'
            - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]
          StopTimeout: 10
      Cpu: 256
      ExecutionRoleArn: !GetAtt HelloRoleTaskExecution.Arn
      Family: !Sub
        - 'hello-task-family-${UniqueSuffix}'
        - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]
      Memory: 512
      Tags: 
        - Key: 'Name'
          Value: 'Hello Task'

  #===== IAM
  HelloRoleTaskExecution:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect: 'Allow'
          Principal: 
            Service: 
              - 'ecs-tasks.amazonaws.com'
          Action: 
            - 'sts:AssumeRole'
      Description: 'Hello Role'
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
      RoleName: !Sub
        - 'hello-role-${UniqueSuffix}'
        - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]