Mappings:
  Application:
    Settings:
      AvailabilityZone: 'us-east-1a'
      UniqueSuffix: 'e02'

Resources: 
  #===== NACL
  HelloNacl: 
    Type: AWS::EC2::NetworkAcl
    Properties: 
      Tags: 
        - Key: 'Name' 
          Value: !Sub
            - 'Hello NACL ${UniqueSuffix}'
            - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]
      VpcId: !Ref HelloVpc 
  
  HelloNaclAssociate: 
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties: 
      NetworkAclId: !Ref HelloNacl 
      SubnetId: !Ref HelloSubnet 

  HelloNaclEntryDenyPing: 
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 1.1.1.1/32
      Egress: true
      Icmp: 
        Code: -1
        Type: -1
      NetworkAclId: !Ref HelloNacl 
      Protocol: 1
      RuleAction: 'deny'
      RuleNumber: 93

  HelloNaclEntryAllowIPv4Ingress: 
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: '0.0.0.0/0'
      Egress: false
      Icmp: 
        Code: -1
        Type: -1
      NetworkAclId: !Ref HelloNacl 
      Protocol: -1
      RuleAction: 'allow'
      RuleNumber: 94

  HelloNaclEntryAllowIPv4Egress: 
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: '0.0.0.0/0'
      Egress: true
      NetworkAclId: !Ref HelloNacl 
      Protocol: -1
      RuleAction: 'allow'
      RuleNumber: 95
  
  #===== EC2 Instance
  HelloInstance: 
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: !FindInMap [ Application, Settings, AvailabilityZone ]
      IamInstanceProfile: !Ref HelloInstanceProfile
      ImageId: ami-04bf6dcdc9ab498ca
      InstanceType: 't2.micro'
      SubnetId: !Ref HelloSubnet 
      Tags: 
        - Key: 'Name'
          Value: !Sub
            - 'Hello instance ${UniqueSuffix}'
            - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]

  #===== IAM
  HelloRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect: 'Allow'
          Principal: 
            Service: 
              - 'ec2.amazonaws.com'
          Action: 
            - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      RoleName: !Sub
        - 'hello-role-${UniqueSuffix}'
        - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]

  HelloInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub
        - 'hello-instance-profile-${UniqueSuffix}'
        - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]
      Roles: 
        - !Ref HelloRole

  #===== VPC + IGW
  HelloVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.16.0.0/16'
      Tags: 
        - Key: 'Name'
          Value: !Sub
            - 'Hello VPC ${UniqueSuffix}'
            - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]
  
  HelloIgw:
    Type: AWS::EC2::InternetGateway
      
  HelloVpcIgwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref HelloIgw 
      VpcId: !Ref HelloVpc

  #===== Subnet
  HelloSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !FindInMap [ Application, Settings, AvailabilityZone ]
      CidrBlock: '10.16.0.0/24'
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: 'Name'
          Value: !Sub
            - 'Hello subnet ${UniqueSuffix}'
            - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]
      VpcId: !Ref HelloVpc

  #===== Route Table
  HelloRt:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: 'Name'
          Value: !Sub
            - 'Hello RT ${UniqueSuffix}'
            - UniqueSuffix: !FindInMap [ Application, Settings, UniqueSuffix ]
      VpcId: !Ref HelloVpc

  HelloRouteIPv4:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref HelloIgw 
      RouteTableId: !Ref HelloRt   

  HelloRtAssociate:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref HelloRt 
      SubnetId: !Ref HelloSubnet
