version: 0.2
 
phases:
  install:
    commands:
      - echo "Hello build phase."
      - pwd
      - ls
      - whoami
      - chmod 777 app.sh
    finally:
      - echo "Hello install phase cleanup."
  pre_build:
    commands:
      - echo "Hello pre-build phase."
  build:
    commands:
      - ./app.sh
  post_build:
    finally:
      - echo "Hello post-build phase cleanup."
      - cat ./AppSpec-L1.yml
      
artifacts:
  files: ./AppSpec-L1.yml